### ISSUE TITLE
Rust Meetup Discord Server aufsetzen

### ISSUE THREAD

**Issue by rstropek** [coding-club-linz/rust-meetup-concept#10]

**Comment by pkim** [comment]
https://discord.gg/BGYBHa
erledigt :) die Rechte-Feineinstellung sollte wir uns dann denk ich gemeinsam überlegen.
Habe jetzt einmal Admin & Speaker angelegt

**Comment by rstropek** [comment]
@pkim Kannst du einen neuen Invite erstellen? Ich glaub, du hast beim Invite ein Expiration Date angegeben bzw. es nicht ausgeschaltet. Daher ist der Link abgelaufen.

**Comment by pkim** [comment]
Stimmt, hier ein Link der nicht abläuft https://discord.gg/T27Ms2f

**Comment by rstropek** [comment]
Kannst du mich zum Admin machen?

**Comment by pkim** [comment]
Habt dir auch gleich die Eigentumsrechte übertragen :)

**Comment by rstropek** [comment]
Danke!
