### ISSUE TITLE
Twitter Plan for First Meetup

### ISSUE THREAD

**Issue by rstropek** [coding-club-linz/rust-meetup-concept#14]
Roughly four weeks until the first Rust Linz meetup. Here is a suggestion for tweets in the next weeks. @ddprrt, can you care for phrasing and sending the tweets?

* [x] Announce first meetup incl. [link to meetup.com](https://www.meetup.com/de-DE/Rust-Linz/events/271857182/)
* [x] Point out [website of Rust Linz](https://rust-linz.at) (wait until confirmation of @karin112358 that first version is complete)
* [x] Point out Ryan as speaker in first meetup
* [x] Invite people to suggest sessions [on sessionize](https://sessionize.com/rust-linz/)
* [x] Announce dates for second and third meetups incl. speaker announcements (wait until we have confirmed speakers; nbf July 20th)
* [x] Invite people to our Discord server ([invite link](https://discord.gg/T27Ms2f)), a week or two before the event

Further ideas for tweets are welcome. @pkim @karin112358 @cschwendtner please retweet.

**Comment by ddprrt** [comment]
Sure 😎

**Comment by ddprrt** [comment]
Upcoming - Checkbox means scheduled

- [x] Reminder 1st Meetup - Week of Jul 20
- [x] Abstract Ryan - Week of Jul 20
- [x] Abstract Rainer - Week of Jul 20
- [x] From the Community - Week of Jul 20
- [x] Two more dates! - Week of Jul 27
- [x] Announcement Meaghan - Week of Jul 27
- [x] Announcement Rucky - Week of Jul 27
- [x] Reminder 1st Meetup - Week of Jul 27
- [x] Reminder Discord - Week of Jul 27
- [x] Coding Club Mention - Week of Jul 27
- [x] From the Community - Week of Jul 27
- [x] Reminder 1st Meetup - Week of Aug 3
- [x] Reminder 1st Meetup - Day before
- [ ] Announcement 2nd Meetup - Week of Aug 3
- [ ] Announcement Meaghan - Week of Aug 3
- [ ] Announcement Rucky - Week of Aug 10
- [ ] Announcement 3rd Meetup - Week of Aug 10
- [ ] Announcement Valentin - Week of Aug 10
- [ ] Announcement Matthias - Week of Aug 10
- [ ] From the Community - Week of Aug 10
