### ISSUE TITLE
Logo überarbeiten lassen

### ISSUE THREAD

**Issue by rstropek** [coding-club-linz/rust-meetup-concept#2]
In Arbeit

**Comment by rstropek** [comment]
Logoenwürfe:

[Rust Linz Entwürfe.pdf](https://github.com/coding-club-linz/rust-meetup-concept/files/4753044/Rust.Linz.Entwurfe.pdf)

Feedback welcome!

**Comment by pkim** [comment]
Ich finde das auf der 2ten Seite am besten. Wahrscheinlich ein dumme Frage, aber haben die Farben bei Linz einen bestimmten Grund? Auf den ersten Blick haben sie mich an die [LGBT](https://de.wikipedia.org/wiki/LGBT)-Bewegung erinnert.

**Comment by rstropek** [comment]
Das farbige _Linz_ kommt aus dem CoderDojo-Logo:
![image](https://user-images.githubusercontent.com/2341573/84639456-b0d39480-aef8-11ea-83ed-20d6d3c37b1e.png)

Ich fände es super, wenn es über alle Initiativen des Coding Club Linz e.V. das _Linz_ als Wiedererkennungsfaktor gibt.

Im weitesten Sinn ist das _Linz_ inspiriert durch das Ars Electronica Logo, das auch einen starken Linz-Bezug hat:
![image](https://user-images.githubusercontent.com/2341573/84639656-f5f7c680-aef8-11ea-9cf1-ed152ca4dcde.png)

**Comment by rstropek** [comment]
Beim Designer wegen SVGs angefragt.

**Comment by rstropek** [comment]
Logos (SVG, PNG) stehen unter https://codingclublinz.sharepoint.com/:f:/g/Dokumente/EmhJ-7t6BsZGlyw9g8DQwyABXdCs6qf5kwzRk3sx_UkfCw?e=A7MxrU zur Verfügung.
