### ISSUE TITLE
Twitter account

### ISSUE THREAD

**Issue by ddprrt** [coding-club-linz/rust-meetup-concept#5]
Hab soeben https://twitter.com/rustlinz registriert. Im Moment noch auf eine persönliche Adresse, die ich gerne auf eine "ordentliche" @rust-linz.at ändere :)

Bitte nennt mir eure Twitter Accounts, ich mach mal einen Basis-Follow.

**Comment by rstropek** [comment]
Danke! Schon im Konzept verlinkt. Ich folge schon.
