### ISSUE TITLE
Diskussion: Meetup Sprache

### ISSUE THREAD

**Issue by ddprrt** [coding-club-linz/rust-meetup-concept#6]
Vielleicht etwas für den initialen Termin: Welche Meetup-Sprache wollen wir?

Kurze Geschichte wie es bei Stahlstadt.js lief.

1. Kommunikation und Meetup Sprache war ursprünglich Deutsch
2. Mit Meetup 8 war die Kommunikation verpflichtend Englisch, Vorträge auf Deutsch wenn kein Nicht-Deutsch-Sprechender anwesend war
3. Mit Meetup 16 waren auch die Vorträge verpflichtend Englisch, weil später alle auf YouTube gezeigt wurden.

**Comment by rstropek** [comment]
Englisch, Ausnahmen denkbar.
