### ISSUE TITLE
Meetup Gruppe

### ISSUE THREAD

**Issue by ddprrt** [coding-club-linz/rust-meetup-concept#7]
Meetup.com als Meetup Org Platform ist schon sehr etabliert und funktioniert auch sehr gut, hat allerdings auch ein Preismarkerl: https://help.meetup.com/hc/de/articles/360001620472-Preise-f%C3%BCr-Organisatoren-Abonnements

Sponsoring von Rust selbst gibt es nicht (vgl. Sponsoring .NET Meetups)

Abwägung Vor- / Nachteile. Ev. auch Vergleich mit anderen Meetup Gruppen im Rust Sektor bzw. in Linz. 

Links:
- https://www.meetup.com/de-DE/topics/rust/
- https://help.meetup.com/hc/de/articles/360001620472-Preise-f%C3%BCr-Organisatoren-Abonnements

**Comment by rstropek** [comment]
Die Preise sind für bis zu drei Gruppen. Gibt es in Linz vielleicht Communities, an die wir uns z.B. gegen Kostenbeteiligung dranhängen können? Weiß da jemand was?

**Comment by ddprrt** [comment]
Das wusste ich nicht, aber ich glaube da finden wir was :-) 
Ansonsten kann ich überlegen, dass fettblog.eu sponsort. Das könnte ich mit dem Relaunch gleichziehen --> https://ddprrt-github-io-git-11ty.ddprrt.now.sh/

**Comment by ddprrt** [comment]
Ich hab mal bei meinen Kollegen vorgefragt. Kann sein, dass ich schon in die Urlaubszeit rutsche

**Comment by ddprrt** [comment]
Well: https://www.meetup.com/de-DE/Rust-Linz/
Info: Stefan Gusenbauer hostet das Hagenberg Tech Meetup und zahlt mit seinem Account unsere Gruppe. Deswegen scheint er hier als Organiser auf. Das stört uns denke ich nicht, ihn glaub ich auch nicht ;-)
