### ISSUE TITLE
Erste Termine fixieren

### ISSUE THREAD

**Issue by rstropek** [coding-club-linz/rust-meetup-concept#9]
- [x] Rhythmus festlegen
- [x] Termine für erste 3 Monate festlegen -> Doodle

**Comment by rstropek** [comment]
- August erstes Meetup
- solange Online, monatlich
- wenn später in-Person, vielleicht weniger häufig

**Comment by pkim** [comment]
Hier der [https://doodle.com/poll/6figf9a9a5ta8hab](Doodle) :)
Montags und Mittwochs bin ich leider Abends immer schon verplant. 
Diese Termine könnte ich zwar einzeln pro Monat absagen, aber vielleicht findet sich ja ein anderer Tag :)

**Comment by rstropek** [comment]
Broken Link, hier der korrigierte Link zum Doodle: https://doodle.com/poll/6figf9a9a5ta8hab

**Comment by rstropek** [comment]
Wg. CoderDojos ist Freitag immer schlecht -> Di oder Do würde nicht schlecht passen. Habe die bei mir leicht möglichen Termine im Doodle markiert. @karin112358, @ddprrt, @cschwendtner könntet ihr eure möglichen Termine ergänzen?

**Comment by rstropek** [comment]
Bisher sehen die Donnerstage nicht schlecht aus. Folgende Termine gehen bisher bei allen:

* 6.8.
* 17.9. (etwas später im Monat, weil Anfang September das Ars Electronica Festival ist)
* 8.10.

@ddprrt Wie würden diese Tage bei dir aussehen?

**Comment by ddprrt** [comment]
Ja die Tage gehen viel besser wenn man Github Notifications eingeschaltet hätte um zeitgerecht zu antworten 🙈 
Die Termine passen gut :-)
